import { Config } from "effect"

function env(primary: string, fallback?: string) {
  return process.env[primary] ?? (fallback ? process.env[fallback] : undefined)
}

function truthy(key: string, fallback?: string) {
  const value = env(key, fallback)?.toLowerCase()
  return value === "true" || value === "1"
}

const OPENCODE_EXPERIMENTAL = truthy("KIDUCODE_EXPERIMENTAL", "OPENCODE_EXPERIMENTAL")
const copy = env("KIDUCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENCODE_AUTO_HEAP_SNAPSHOT: truthy("KIDUCODE_AUTO_HEAP_SNAPSHOT", "OPENCODE_AUTO_HEAP_SNAPSHOT"),
  OPENCODE_GIT_BASH_PATH: env("KIDUCODE_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH"),
  OPENCODE_CONFIG: env("KIDUCODE_CONFIG", "OPENCODE_CONFIG"),
  OPENCODE_CONFIG_CONTENT: env("KIDUCODE_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT"),
  OPENCODE_DISABLE_AUTOUPDATE: truthy("KIDUCODE_DISABLE_AUTOUPDATE", "OPENCODE_DISABLE_AUTOUPDATE"),
  OPENCODE_ALWAYS_NOTIFY_UPDATE: truthy("KIDUCODE_ALWAYS_NOTIFY_UPDATE", "OPENCODE_ALWAYS_NOTIFY_UPDATE"),
  OPENCODE_DISABLE_PRUNE: truthy("KIDUCODE_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE"),
  OPENCODE_DISABLE_TERMINAL_TITLE: truthy("KIDUCODE_DISABLE_TERMINAL_TITLE", "OPENCODE_DISABLE_TERMINAL_TITLE"),
  OPENCODE_SHOW_TTFD: truthy("KIDUCODE_SHOW_TTFD", "OPENCODE_SHOW_TTFD"),
  OPENCODE_DISABLE_AUTOCOMPACT: truthy("KIDUCODE_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT"),
  OPENCODE_DISABLE_MODELS_FETCH: truthy("KIDUCODE_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH"),
  OPENCODE_DISABLE_MOUSE: truthy("KIDUCODE_DISABLE_MOUSE", "OPENCODE_DISABLE_MOUSE"),
  OPENCODE_FAKE_VCS: env("KIDUCODE_FAKE_VCS", "OPENCODE_FAKE_VCS"),
  OPENCODE_SERVER_PASSWORD: env("KIDUCODE_SERVER_PASSWORD", "OPENCODE_SERVER_PASSWORD"),
  OPENCODE_SERVER_USERNAME: env("KIDUCODE_SERVER_USERNAME", "OPENCODE_SERVER_USERNAME"),

  // Experimental
  OPENCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined
      ? process.platform === "win32"
      : truthy("KIDUCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENCODE_MODELS_URL: env("KIDUCODE_MODELS_URL", "OPENCODE_MODELS_URL"),
  OPENCODE_MODELS_PATH: env("KIDUCODE_MODELS_PATH", "OPENCODE_MODELS_PATH"),
  OPENCODE_DB: env("KIDUCODE_DB", "OPENCODE_DB"),

  OPENCODE_WORKSPACE_ID: env("KIDUCODE_WORKSPACE_ID", "OPENCODE_WORKSPACE_ID"),
  OPENCODE_EXPERIMENTAL_WORKSPACES:
    OPENCODE_EXPERIMENTAL || truthy("KIDUCODE_EXPERIMENTAL_WORKSPACES", "OPENCODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("KIDUCODE_DISABLE_PROJECT_CONFIG", "OPENCODE_DISABLE_PROJECT_CONFIG")
  },
  get OPENCODE_TUI_CONFIG() {
    return env("KIDUCODE_TUI_CONFIG", "OPENCODE_TUI_CONFIG")
  },
  get OPENCODE_CONFIG_DIR() {
    return env("KIDUCODE_CONFIG_DIR", "OPENCODE_CONFIG_DIR")
  },
  get OPENCODE_PURE() {
    return truthy("KIDUCODE_PURE", "OPENCODE_PURE")
  },
  get OPENCODE_PERMISSION() {
    return env("KIDUCODE_PERMISSION", "OPENCODE_PERMISSION")
  },
  get OPENCODE_PLUGIN_META_FILE() {
    return env("KIDUCODE_PLUGIN_META_FILE", "OPENCODE_PLUGIN_META_FILE")
  },
  get OPENCODE_CLIENT() {
    return env("KIDUCODE_CLIENT", "OPENCODE_CLIENT") ?? "cli"
  },
}
